from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Project(object):
    def setupUi(self, Project):
        Project.setObjectName("Project")
        Project.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(Project)
        self.centralwidget.setObjectName("centralwidget")
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        self.main_label.setGeometry(QtCore.QRect(0, -1, 900, 111))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.main_label.setFont(font)
        self.main_label.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(242, 255, 244);")
        self.main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label.setObjectName("main_label")
        self.main_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tabs.setGeometry(QtCore.QRect(0, 80, 901, 521))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.main_tabs.setFont(font)
        self.main_tabs.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.main_tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.main_tabs.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.main_tabs.setIconSize(QtCore.QSize(20, 20))
        self.main_tabs.setElideMode(QtCore.Qt.ElideLeft)
        self.main_tabs.setTabsClosable(False)
        self.main_tabs.setObjectName("main_tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.portcomboBox = QtWidgets.QComboBox(self.tab)
        self.portcomboBox.setGeometry(QtCore.QRect(240, 40, 141, 31))
        self.portcomboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.portcomboBox.setObjectName("portcomboBox")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(90, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(80, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.speedcomboBox = QtWidgets.QComboBox(self.tab)
        self.speedcomboBox.setGeometry(QtCore.QRect(240, 100, 141, 31))
        self.speedcomboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.speedcomboBox.setObjectName("speedcomboBox")
        self.main_tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.temperatureLabel = QtWidgets.QLabel(self.tab_2)
        self.temperatureLabel.setGeometry(QtCore.QRect(100, 50, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.temperatureLabel.setFont(font)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.dispTemperature = QtWidgets.QLabel(self.tab_2)
        self.dispTemperature.setGeometry(QtCore.QRect(240, 50, 131, 31))
        self.dispTemperature.setAlignment(QtCore.Qt.AlignCenter)
        self.dispTemperature.setObjectName("dispTemperature")
        self.humidityLabel = QtWidgets.QLabel(self.tab_2)
        self.humidityLabel.setGeometry(QtCore.QRect(110, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.humidityLabel.setFont(font)
        self.humidityLabel.setObjectName("humidityLabel")
        self.dispHumidity = QtWidgets.QLabel(self.tab_2)
        self.dispHumidity.setGeometry(QtCore.QRect(240, 100, 131, 31))
        self.dispHumidity.setAlignment(QtCore.Qt.AlignCenter)
        self.dispHumidity.setObjectName("dispHumidity")
        self.refreshButton = QtWidgets.QPushButton(self.tab_2)
        self.refreshButton.setGeometry(QtCore.QRect(690, 420, 151, 31))
        self.refreshButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refreshButton.setStyleSheet("background-color: rgb(239, 255, 240);")
        self.refreshButton.setObjectName("refreshButton")
        self.advice1 = QtWidgets.QLabel(self.tab_2)
        self.advice1.setGeometry(QtCore.QRect(60, 250, 811, 31))
        self.advice1.setObjectName("advice1")
        self.advice2 = QtWidgets.QLabel(self.tab_2)
        self.advice2.setGeometry(QtCore.QRect(60, 290, 811, 31))
        self.advice2.setObjectName("advice2")
        self.adviceLabel = QtWidgets.QLabel(self.tab_2)
        self.adviceLabel.setGeometry(QtCore.QRect(60, 210, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adviceLabel.setFont(font)
        self.adviceLabel.setObjectName("adviceLabel")
        self.advice3 = QtWidgets.QLabel(self.tab_2)
        self.advice3.setGeometry(QtCore.QRect(60, 330, 811, 31))
        self.advice3.setObjectName("advice3")
        self.nextWatering = QtWidgets.QLabel(self.tab_2)
        self.nextWatering.setGeometry(QtCore.QRect(430, 70, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextWatering.setFont(font)
        self.nextWatering.setObjectName("nextWatering")
        self.nextWateringTime = QtWidgets.QLabel(self.tab_2)
        self.nextWateringTime.setGeometry(QtCore.QRect(660, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextWateringTime.setFont(font)
        self.nextWateringTime.setObjectName("nextWateringTime")
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(403, 0, 20, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(-3, 160, 901, 20))
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.timeMeasurementLabel = QtWidgets.QLabel(self.tab_2)
        self.timeMeasurementLabel.setGeometry(QtCore.QRect(430, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeMeasurementLabel.setFont(font)
        self.timeMeasurementLabel.setObjectName("timeMeasurementLabel")
        self.timeOfMeasurement = QtWidgets.QLabel(self.tab_2)
        self.timeOfMeasurement.setGeometry(QtCore.QRect(660, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeOfMeasurement.setFont(font)
        self.timeOfMeasurement.setObjectName("timeOfMeasurement")
        self.lastWateringLabel = QtWidgets.QLabel(self.tab_2)
        self.lastWateringLabel.setGeometry(QtCore.QRect(430, 110, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastWateringLabel.setFont(font)
        self.lastWateringLabel.setObjectName("lastWateringLabel")
        self.lastWateringTime = QtWidgets.QLabel(self.tab_2)
        self.lastWateringTime.setGeometry(QtCore.QRect(660, 110, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastWateringTime.setFont(font)
        self.lastWateringTime.setObjectName("lastWateringTime")
        self.main_tabs.addTab(self.tab_2, "")
        Project.setCentralWidget(self.centralwidget)

        self.retranslateUi(Project)
        self.main_tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Project)

    def retranslateUi(self, Project):
        _translate = QtCore.QCoreApplication.translate
        Project.setWindowTitle(_translate("Project", "Project"))
        self.main_label.setText(_translate("Project", "Smart Flower pot"))
        self.label.setText(_translate("Project", "Select port:"))
        self.label_3.setText(_translate("Project", "Select speed:"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.tab), _translate("Project", "Ports"))
        self.temperatureLabel.setText(_translate("Project", "Temperature:"))
        self.dispTemperature.setText(_translate("Project", "NO DATA"))
        self.humidityLabel.setText(_translate("Project", "Humidity:"))
        self.dispHumidity.setText(_translate("Project", "NO DATA"))
        self.refreshButton.setText(_translate("Project", "Get data"))
        self.advice1.setText(_translate("Project", "-"))
        self.advice2.setText(_translate("Project", "-"))
        self.adviceLabel.setText(_translate("Project", "Advices:"))
        self.advice3.setText(_translate("Project", "-"))
        self.nextWatering.setText(_translate("Project", "Next watering time:"))
        self.nextWateringTime.setText(_translate("Project", "NO DATA"))
        self.timeMeasurementLabel.setText(_translate("Project", "Time of measurement:"))
        self.timeOfMeasurement.setText(_translate("Project", "NO DATA"))
        self.lastWateringLabel.setText(_translate("Project", "Last watering time:"))
        self.lastWateringTime.setText(_translate("Project", "NO DATA"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.tab_2), _translate("Project", "Flower pot control"))
